site_name: THUNDER
repo_name: MICS-Lab/thunder
site_url: https://mics-lab.github.io/thunder
repo_url: https://github.com/MICS-Lab/thunder

extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/datatables.net-bs5@1.13.7/css/dataTables.bootstrap5.min.css
  - https://cdn.datatables.net/searchpanes/2.3.3/css/searchPanes.dataTables.min.css

extra_javascript:
  - https://code.jquery.com/jquery-3.7.1.min.js
  - https://cdn.jsdelivr.net/npm/datatables.net@1.13.7/js/jquery.dataTables.min.js
  - https://cdn.jsdelivr.net/npm/datatables.net-bs5@1.13.7/js/dataTables.bootstrap5.min.js

  - https://cdn.datatables.net/select/1.3.1/js/dataTables.select.min.js
  - https://cdn.datatables.net/searchpanes/2.3.3/js/dataTables.searchPanes.min.js

  - javascripts/rank-table.js

nav:
  - Home: index.md
  - Leaderboard: leaderboard.md 
  - Tutorials:
    - Getting Started: getting_started.md
    - Benchmarking a Custom Model: custom_model.md
    - Overriding Configurations: custom_config.md
    - Using foundation models on your data: get_model.md
  - API: api.md

theme: 
  name: material
  logo: logo.svg
  favicon: logo.svg
  palette:
    primary: deep purple

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            heading_level: 3

markdown_extensions:
  - md_in_html               
  - attr_list              
  - admonition
  - pymdownx.details
  - pymdownx.superfences

