dataset_name: bach
nb_classes: 4
base_data_folder: ${oc.env:THUNDER_BASE_DATA_FOLDER}/datasets/
compatible_tasks: ["alignment_scoring",  "embedding_space_visualization", "emir", "image_retrieval", "knn", "knn_ensembling", "linear_probing", "pre_computing_embeddings", "simple_shot", "transformation_invariance", "adversarial_attack"]
nb_train_samples: 218
nb_val_samples: 50
nb_test_samples: 132
md5sum: "6b1a33fab172d8d626714978ae08f09f"
image_sizes: [[2048, 1536]]
mpp: 0.42
cancer_type: breast
classes: ["Benign", "InSitu", "Invasive", "Normal"]
class_to_id:
  Benign: 0
  InSitu: 1
  Invasive: 2
  Normal: 3
id_to_class:
  0: Benign
  1: InSitu
  2: Invasive
  3: Normal
