dataset_name: bracs
nb_classes: 7
base_data_folder: ${oc.env:THUNDER_BASE_DATA_FOLDER}/datasets/
compatible_tasks: ["alignment_scoring",  "embedding_space_visualization", "emir", "image_retrieval", "knn", "knn_ensembling", "linear_probing", "pre_computing_embeddings", "simple_shot", "adversarial_attack"]
nb_train_samples: 3657 
nb_val_samples: 312
nb_test_samples: 570
md5sum: "01c7e920954ab105d20e17616e648324"
mpp: 0.25
cancer_type: breast
classes: ["0_N", "1_PB", "2_UDH", "3_FEA", "4_ADH", "5_DCIS", "6_IC"]
class_to_id:
  0_N: 0
  1_PB: 1
  2_UDH: 2
  3_FEA: 3
  4_ADH: 4
  5_DCIS: 5
  6_IC: 6
id_to_class:
  0: 0_N
  1: 1_PB
  2: 2_UDH
  3: 3_FEA
  4: 4_ADH
  5: 5_DCIS
  6: 6_IC
