dataset_name: break_his
nb_classes: 4
base_data_folder: ${oc.env:THUNDER_BASE_DATA_FOLDER}/datasets/
compatible_tasks: ["adversarial_attack", "alignment_scoring", "image_retrieval", "knn", "linear_probing", "pre_computing_embeddings", "simple_shot", "transformation_invariance", "zero_shot_vlm"]
nb_train_samples: 936
nb_val_samples: 196 
nb_test_samples: 339
md5sum: "e729da1a4390a56aa9889aac0baf4688"
image_sizes: [[700, 460]]
mpp: 0.25
cancer_type: breast
classes: ["fibroadenoma", "tubular_adenoma", "ductal_carcinoma", "mucinous_carcinoma"]
class_to_id:
  fibroadenoma: 0
  tubular_adenoma: 1
  ductal_carcinoma: 2
  mucinous_carcinoma: 3
id_to_class:
  0: fibroadenoma
  1: tubular_adenoma
  2: ductal_carcinoma
  3: mucinous_carcinoma
id_to_classname:
  0: breast fibroadenoma
  1: breast tubular adenoma
  2: breast ductal carcinoma
  3: breast mucinous carcinoma