dataset_name: ccrcc
nb_classes: 3
base_data_folder: ${oc.env:THUNDER_BASE_DATA_FOLDER}/datasets/
compatible_tasks: ["adversarial_attack", "alignment_scoring", "image_retrieval", "knn", "linear_probing", "pre_computing_embeddings", "simple_shot", "transformation_invariance", "zero_shot_vlm"]
nb_train_samples: 16797
nb_val_samples: 4298
nb_test_samples: 6074
md5sum: "9d7e35574690d0458c10ad3ff7359c80"
image_sizes: [[256, 256] , [300, 300]]
mpp: 0.25
cancer_type: renal
classes: ["cancer", "normal", "stroma"]
class_to_id:
  cancer: 0
  normal: 1
  stroma: 2
id_to_class:
  0: cancer
  1: normal
  2: stroma
id_to_classname:
  0: cancerous renal tissue
  1: normal renal tissue
  2: renal stroma