dataset_name: crc
nb_classes: 9
base_data_folder: ${oc.env:THUNDER_BASE_DATA_FOLDER}/datasets/
compatible_tasks: ["adversarial_attack", "alignment_scoring", "image_retrieval", "knn", "linear_probing", "pre_computing_embeddings", "simple_shot", "transformation_invariance", "zero_shot_vlm"]
nb_train_samples: 80000
nb_val_samples: 20000
nb_test_samples: 7180
md5sum: "38d27a33832f0e44c767a7011d7138dd"
image_sizes: [[224, 224]]
mpp: 0.5
cancer_type: colorectal
classes: ["ADI", "BACK", "DEB", "LYM", "MUC", "MUS", "NORM", "STR", "TUM"]
class_to_id:
  ADI: 0
  BACK: 1
  DEB: 2
  LYM: 3
  MUC: 4
  MUS: 5
  NORM: 6
  STR: 7
  TUM: 8
id_to_class:
  0: ADI
  1: BACK
  2: DEB
  3: LYM
  4: MUC
  5: MUS
  6: NORM
  7: STR
  8: TUM
id_to_classname: # From KEEP paper
  0: adipose
  1: background
  2: debris
  3: lymphocytes
  4: mucus
  5: smooth muscle
  6: normal colon mucosa
  7: cancer-associated stroma
  8: colorectal adenocarcinoma epithelium