dataset_name: esca
nb_classes: 11
base_data_folder: ${oc.env:THUNDER_BASE_DATA_FOLDER}/datasets/
compatible_tasks: ["adversarial_attack", "alignment_scoring", "image_retrieval", "knn", "linear_probing", "pre_computing_embeddings", "simple_shot", "transformation_invariance", "zero_shot_vlm"]
nb_train_samples: 154438
nb_val_samples: 34704
nb_test_samples: 178187
image_sizes: [[256, 256]]
md5sum: "d847c467c5789a74b6268dab84d7d7cf"
mpp: 0.78
cancer_type: oesophageal
classes: ["ADVENT", "LAM_PROP", "MUSC_MUC", "MUSC_PROP", "REGR_TU", "SH_MAG", "SH_OES", "SUB_GL", "SUBMUC", "TUMOR", "ULCUS"]
class_to_id:
  ADVENT: 0
  LAM_PROP: 1
  MUSC_MUC: 2
  MUSC_PROP: 3
  REGR_TU: 4
  SH_MAG: 5
  SH_OES: 6
  SUB_GL: 7
  SUBMUC: 8
  TUMOR: 9
  ULCUS: 10
id_to_class:
  0: ADVENT
  1: LAM_PROP
  2: MUSC_MUC
  3: MUSC_PROP
  4: REGR_TU
  5: SH_MAG
  6: SH_OES
  7: SUB_GL
  8: SUBMUC
  9: TUMOR
  10: ULCUS
id_to_classname:
  0: adventitia
  1: lamina propria mucosae
  2: muscularis mucosae
  3: muscularis propria
  4: regression tissue
  5: mucosa gastric
  6: muscosa esophagus
  7: sub-mucosa
  8: submucosal glands
  9: oesophageal tumor
  10: ulceration