dataset_name: mhist
nb_classes: 2
base_data_folder: ${oc.env:THUNDER_BASE_DATA_FOLDER}/datasets/
compatible_tasks: ["adversarial_attack", "alignment_scoring", "image_retrieval", "knn", "linear_probing", "pre_computing_embeddings", "simple_shot", "transformation_invariance", "zero_shot_vlm"]
nb_train_samples: 1743
nb_val_samples: 432
nb_test_samples: 977
md5sum: "81d623fc3a740acffa23a1e58d90a8d2"
image_sizes: [[224, 224]]
mpp: 2.0
cancer_type: colorectal
classes: ["HP", "SSA"]
class_to_id:
  HP: 0
  SSA: 1
id_to_class:
  0: HP
  1: SSA
id_to_classname: # From Quiltnet paper
  0: hyperplastic polyp
  1: sessile serrated adenoma