dataset_name: patch_camelyon
nb_classes: 2
base_data_folder: ${oc.env:THUNDER_BASE_DATA_FOLDER}/datasets/
compatible_tasks: ["adversarial_attack", "alignment_scoring", "image_retrieval", "knn", "linear_probing", "pre_computing_embeddings", "simple_shot", "transformation_invariance", "zero_shot_vlm"]
nb_train_samples: 262144
nb_val_samples: 32768
nb_test_samples: 32768
image_sizes: [[96, 96]]
mpp: 1.0
cancer_type: breast
classes: ["no-metastatic-tissue", "metastatic-tissue"]
class_to_id:
  no-metastatic-tissue: 0
  metastatic-tissue: 1
id_to_class:
  0: no-metastatic-tissue
  1: metastatic-tissue
id_to_classname: # From Quiltnet and CLIP papers
  0: lymph node
  1: lymph node containing metastatic tumor tissue