dataset_name: tcga_tils
nb_classes: 2
base_data_folder: ${oc.env:THUNDER_BASE_DATA_FOLDER}/datasets/
compatible_tasks: ["adversarial_attack", "alignment_scoring", "image_retrieval", "knn", "linear_probing", "pre_computing_embeddings", "simple_shot", "transformation_invariance", "zero_shot_vlm"]
nb_train_samples: 209221
nb_val_samples: 38601
nb_test_samples: 56275
md5sum: "d03d5d4fed87afd67d10e9501c97977d"
image_sizes: [[100, 100]]
mpp: 0.5
cancer_type: pan_cancer
classes: ["til-negative", "til-positive"]
class_to_id:
  til-negative: 0
  til-positive: 1
id_to_class:
  0: til-negative
  1: til-positive
id_to_classname:
  0: tissue
  1: tissue containing tumor-infiltrating lymphocytes