dataset_name: tcga_crc_msi
nb_classes: 2
base_data_folder: ${oc.env:THUNDER_BASE_DATA_FOLDER}/datasets/
compatible_tasks: ["adversarial_attack", "alignment_scoring", "image_retrieval", "knn", "linear_probing", "pre_computing_embeddings", "simple_shot", "transformation_invariance", "zero_shot_vlm"]
nb_train_samples: 14762
nb_val_samples: 4795
nb_test_samples: 32361
md5sum: "457fbda87ed5ae86062f1517dc3474ab"
image_sizes: [[512, 512]]
mpp: 0.5
cancer_type: colorectal
classes: ["nonMSIH", "MSIH"]
class_to_id:
  nonMSIH: 0
  MSIH: 1
id_to_class:
  0: nonMSIH
  1: MSIH
id_to_classname:
  0: microsatellite stability
  1: microsatellite instability