dataset_name: tcga_uniform
nb_classes: 32
base_data_folder: ${oc.env:THUNDER_BASE_DATA_FOLDER}/datasets/
compatible_tasks: ["adversarial_attack", "alignment_scoring", "image_retrieval", "knn", "linear_probing", "pre_computing_embeddings", "simple_shot", "transformation_invariance", "zero_shot_vlm"]
nb_train_samples: 170840
nb_val_samples: 44670
nb_test_samples: 56200
md5sum: "8333eb6726562f10f0252037cec94567"
image_sizes: [[256, 256]]
mpp: 0.5
cancer_type: pan_cancer
classes: [
            "Adrenocortical_carcinoma",
            "Bladder_Urothelial_Carcinoma",
            "Brain_Lower_Grade_Glioma",
            "Breast_invasive_carcinoma",
            "Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma",
            "Cholangiocarcinoma",
            "Colon_adenocarcinoma",
            "Esophageal_carcinoma",
            "Glioblastoma_multiforme",
            "Head_and_Neck_squamous_cell_carcinoma",
            "Kidney_Chromophobe",
            "Kidney_renal_clear_cell_carcinoma",
            "Kidney_renal_papillary_cell_carcinoma",
            "Liver_hepatocellular_carcinoma",
            "Lung_adenocarcinoma",
            "Lung_squamous_cell_carcinoma",
            "Lymphoid_Neoplasm_Diffuse_Large_B-cell_Lymphoma",
            "Mesothelioma",
            "Ovarian_serous_cystadenocarcinoma",
            "Pancreatic_adenocarcinoma",
            "Pheochromocytoma_and_Paraganglioma",
            "Prostate_adenocarcinoma",
            "Rectum_adenocarcinoma",
            "Sarcoma",
            "Skin_Cutaneous_Melanoma",
            "Stomach_adenocarcinoma",
            "Testicular_Germ_Cell_Tumors",
            "Thymoma",
            "Thyroid_carcinoma",
            "Uterine_Carcinosarcoma",
            "Uterine_Corpus_Endometrial_Carcinoma",
            "Uveal_Melanoma",
          ]
class_to_id:
  Adrenocortical_carcinoma: 0
  Bladder_Urothelial_Carcinoma: 1
  Brain_Lower_Grade_Glioma: 2
  Breast_invasive_carcinoma: 3
  Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma: 4
  Cholangiocarcinoma: 5
  Colon_adenocarcinoma: 6
  Esophageal_carcinoma: 7
  Glioblastoma_multiforme: 8
  Head_and_Neck_squamous_cell_carcinoma: 9
  Kidney_Chromophobe: 10
  Kidney_renal_clear_cell_carcinoma: 11
  Kidney_renal_papillary_cell_carcinoma: 12
  Liver_hepatocellular_carcinoma: 13
  Lung_adenocarcinoma: 14
  Lung_squamous_cell_carcinoma: 15
  Lymphoid_Neoplasm_Diffuse_Large_B-cell_Lymphoma: 16
  Mesothelioma: 17
  Ovarian_serous_cystadenocarcinoma: 18
  Pancreatic_adenocarcinoma: 19
  Pheochromocytoma_and_Paraganglioma: 20
  Prostate_adenocarcinoma: 21
  Rectum_adenocarcinoma: 22
  Sarcoma: 23
  Skin_Cutaneous_Melanoma: 24
  Stomach_adenocarcinoma: 25
  Testicular_Germ_Cell_Tumors: 26
  Thymoma: 27
  Thyroid_carcinoma: 28
  Uterine_Carcinosarcoma: 29
  Uterine_Corpus_Endometrial_Carcinoma: 30
  Uveal_Melanoma: 31
id_to_class:
  0: Adrenocortical_carcinoma
  1: Bladder_Urothelial_Carcinoma
  2: Brain_Lower_Grade_Glioma
  3: Breast_invasive_carcinoma
  4: Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma
  5: Cholangiocarcinoma
  6: Colon_adenocarcinoma
  7: Esophageal_carcinoma
  8: Glioblastoma_multiforme
  9: Head_and_Neck_squamous_cell_carcinoma
  10: Kidney_Chromophobe
  11: Kidney_renal_clear_cell_carcinoma
  12: Kidney_renal_papillary_cell_carcinoma
  13: Liver_hepatocellular_carcinoma
  14: Lung_adenocarcinoma
  15: Lung_squamous_cell_carcinoma
  16: Lymphoid_Neoplasm_Diffuse_Large_B-cell_Lymphoma
  17: Mesothelioma
  18: Ovarian_serous_cystadenocarcinoma
  19: Pancreatic_adenocarcinoma
  20: Pheochromocytoma_and_Paraganglioma
  21: Prostate_adenocarcinoma
  22: Rectum_adenocarcinoma
  23: Sarcoma
  24: Skin_Cutaneous_Melanoma
  25: Stomach_adenocarcinoma
  26: Testicular_Germ_Cell_Tumors
  27: Thymoma
  28: Thyroid_carcinoma
  29: Uterine_Carcinosarcoma
  30: Uterine_Corpus_Endometrial_Carcinoma
  31: Uveal_Melanoma
id_to_classname:
  0: adrenocortical carcinoma
  1: bladder urothelial carcinoma
  2: brain lower grade glioma
  3: breast invasive carcinoma
  4: cervical squamous cell carcinoma and endocervical adenocarcinoma
  5: cholangiocarcinoma
  6: colon adenocarcinoma
  7: esophageal carcinoma
  8: elioblastoma multiforme
  9: head and neck squamous cell carcinoma
  10: kidney chromophobe
  11: kidney renal clear cell carcinoma
  12: kidney renal papillary cell carcinoma
  13: liver hepatocellular carcinoma
  14: lung adenocarcinoma
  15: lung squamous cell carcinoma
  16: lymphoid neoplasm diffuse large B-cell lymphoma
  17: mesothelioma
  18: ovarian serous cystadenocarcinoma
  19: pancreatic adenocarcinoma
  20: Pheochromocytoma_and_Paraganglioma
  21: prostate adenocarcinoma
  22: rectum adenocarcinoma
  23: sarcoma
  24: skin cutaneous melanoma
  25: stomach adenocarcinoma
  26: testicular germ cell tumors
  27: thymoma
  28: thyroid carcinoma
  29: uterine carcinosarcoma
  30: uterine corpus endometrial carcinoma
  31: uveal melanoma