dataset_name: wilds
nb_classes: 2
base_data_folder: ${oc.env:THUNDER_BASE_DATA_FOLDER}/datasets/
compatible_tasks: ["adversarial_attack", "alignment_scoring", "image_retrieval", "knn", "linear_probing", "pre_computing_embeddings", "simple_shot", "transformation_invariance", "zero_shot_vlm"]
nb_train_samples: 302436
nb_val_samples: 34904
nb_test_samples: 85054
md5sum: "d72954282a51250e942ad0a2384cb16e"
image_sizes: [[96, 96]]
mpp: 1.0
cancer_type: breast
classes: ["NORMAL", "TUMOR"]
class_to_id:
  NORMAL: 0
  TUMOR: 1
id_to_class:
  0: NORMAL
  1: TUMOR
id_to_classname:
  0: lymph node
  1: lymph node containing metastatic tumor tissue