dataset_name: wilds
nb_classes: 2
base_data_folder: ${oc.env:THUNDER_BASE_DATA_FOLDER}/datasets/
compatible_tasks: ["alignment_scoring",  "embedding_space_visualization", "emir", "image_retrieval", "knn", "knn_ensembling", "linear_probing", "pre_computing_embeddings", "simple_shot", "transformation_invariance", "adversarial_attack"]
nb_train_samples: 302436
nb_val_samples: 34904
nb_test_samples: 85054
md5sum: "d72954282a51250e942ad0a2384cb16e"
image_sizes: [[96, 96]]
mpp: 1.0
cancer_type: breast
classes: ["NORMAL", "TUMOR"]
class_to_id:
  NORMAL: 0
  TUMOR: 1
id_to_class:
  0: NORMAL
  1: TUMOR
